### ISSUE TITLE
POST, GET: /user 작동하지 않습니다.

### ISSUE THREAD

**Issue by yoonki1207** [Aunae/aunae-web-backend#18]
post로 createUser가 작동하지 않습니다. class-transformer의 Exclude코드를 제거하면 제대로 작동합니다.
get으로 getUser를 하면 User entity의 Exclude가 있어도 password가 응답됩니다. 
https://github.com/Aunae/aunae-web-backend/blob/main/src/user/user.controller.ts

**Comment by jaewonE** [comment]
@yoonki1207 Exclude 데코레이터 대신 TypeORM의 Column() 데코레이터에서 select: false 를 사용하면 해당 속성을 가져오지 않습니다. 이 경우 getUser를 해도 password가 응답되지 않습니다.
다만 데이터베이스에서 password 속성 값을 가져와야 되는 경우, select: ['password']와 같이 password를 가져오겠다고 지정해주어야 하는데 login과정에서 인증을 어떻게 하는지 확실하게 잘 몰라 메인으로 머지는 하지 않았습니다.
[hotFix-passwordEnclude](https://github.com/Aunae/aunae-web-backend/tree/hotFix-passwordEnclude)

**Comment by yoonki1207** [comment]
인터넷에 찾아보니까 entity가 아니라 dto에 선언을 하던데 그런 방식으로 하면 에러가 해결될까요? 일단 main에 merge되어있어서 코드 실행할때는 Exclude를 주석 처리하고 실행해야 작동하네요.

**Comment by jaewonE** [comment]
dto를 통해 선언할 경우 user에 대한 dto를 생성할 때마다 dto에 password 속성을 선택하지 않겠다고 명시해야 되지 않을까요. 이 경우 중복된 코드 작성이 많아져 비효율적일 것 같습니다. 
위 경우가 아닌 경우 dto에 선언하는 것이 좋을 것 같습니다.

**Comment by KGESH** [comment]
Create User DTO가 PickType으로 변경되어서 발생한 문제 같습니다. 
엔티티의 프로퍼티들을 가져올때 Exclude 데코레이터가 적용된 password 프로퍼티를 가져와 Response 뿐만 아니라 Request에서도 Exclude password가 적용되어 사용자가 password와 함께 POST 요청을 했는데도 걸러지는 문제입니다.

- 이전처럼 DTO에 PickType을 지정하지 말고 독립된 책임을 지는 클래스로 사용한다.
- DTO에 PickType을 사용하고 password 프로퍼티만 따로 정의한다.

이외에 다른 방법들도 서로 논의하고 사용하면 좋을듯합니다. 
다만 처음에 컬럼 데코레이터에서 select 옵션을 false로 지정하는 것도 고려했으나 나중에 쿼리 할 때 일일이 password를 지정해 주는 게 귀찮을듯해서 제외했습니다.

**Comment by jaewonE** [comment]
저는 후자(DTO에 PickType을 사용하고 password 프로퍼티만 따로 정의한다.)가 코드의 중복을 줄이는 방향성이라서 좋을 것 같습니다. 혹시 선배님께서는 어느 방식을 선호하시나요?

**Comment by KGESH** [comment]
저도 PickType 쓰고싶어서 많이 몸 비틀었는데, 말씀 해주신 후자(DTO에 PickType을 사용하고 password 프로퍼티만 따로 정의한다.) 방법도 있고, 이런 방법도 있어요.

`
getUserWithoutPassword(): Omit<User, 'password'> {
  const { password, userWithoutPassword } = 유저 검색;
  return userWithoutPassword;
}
`

**Comment by jaewonE** [comment]
아 좋은것 같습니다! 해당 방법으로 수정해두겠습니다.

**Comment by KGESH** [comment]
저도 아직 어떤 방법이 더 괜찮은지 잘 모르겠어서, 괜찮다면 후자(DTO에 PickType을 사용하고 password 프로퍼티만 따로 정의한다.)로 가도 좋을듯해요.

**Comment by jaewonE** [comment]
음... 그럼 다음 회의(23일) 때 의논하여 최종적으로 결정해 알려드리겠습니다!

**Comment by yoonki1207** [comment]
제 생각에도 PickType에 password 프로퍼티만 따로 하는 방법이 코드 길이를 줄이고, 테이블 컬럼간의 이름도 통일되어서 좋은 것 같습니다. 일단 버그에 대해서는 해결 된 것 같으니 이슈는 close하겠습니다.
